var carData = [
    {
        "id": 0,
        "model": "Model",
        "name": "Audi",
        "mark": "Mark",
        "markNo": "A1",
        "year": "Year",
        "yearNo": "2021",
        "door": "Doors",
        "doorNo": "4/5",
        "ac": "AC",
        "acYes": "Yes",
        "tran": "Transmission",
        "tranManual": "Manual",
        "fuel": "Fuel",
        "fuelDis": "Gasoline",
        "image": "Assets/car1.jpg",
    },
    {
        "id": 1,
        "model": "Model",
        "name": "Golf 6",
        "mark": "Mark",
        "markNo": "Volkswagen",
        "year": "Year",
        "yearNo": "2008",
        "door": "Doors",
        "doorNo": "4/5",
        "ac": "AC",
        "acYes": "Yes",
        "tran": "Transmission",
        "tranManual": "Manual",
        "fuel": "Fuel",
        "fuelDis": "Diesel",
        "image": "Assets/car2.jpg",
    },
    {
        "id": 2,
        "model": "Model",
        "name": "Camry",
        "mark": "Mark",
        "markNo": "Toyota",
        "year": "Year",
        "yearNo": "2006",
        "door": "Doors",
        "doorNo": "4/5",
        "ac": "AC",
        "acYes": "Yes",
        "tran": "Transmission",
        "tranManual": "Automatic",
        "fuel": "Fuel",
        "fuelDis": "Hybrid",
        "image": "Assets/car3.jpg",
    },
    {
        "id": 3,
        "model": "Model",
        "name": "BMW 320",
        "mark": "Mark",
        "markNo": "ModernLine",
        "year": "Year",
        "yearNo": "2013",
        "door": "Doors",
        "doorNo": "4/5",
        "ac": "AC",
        "acYes": "Yes",
        "tran": "Transmission",
        "tranManual": "Manual",
        "fuel": "Fuel",
        "fuelDis": "Petrol",
        "image": "Assets/car4.jpg",
    },
    {
        "id": 4,
        "model": "Model",
        "name": "Mercedes-Benz",
        "mark": "Mark",
        "markNo": "GKL",
        "year": "Year",
        "yearNo": "2015",
        "door": "Doors",
        "doorNo": "4/5",
        "ac": "AC",
        "acYes": "Yes",
        "tran": "Transmission",
        "tranManual": "Manual",
        "fuel": "Fuel",
        "fuelDis": "Gasoline ",
        "image": "Assets/car5.jpg",
    },
    {
        "id": 6,
        "model": "Model",
        "name": "Tesla",
        "mark": "Mark",
        "markNo": "Model S",
        "year": "Year",
        "yearNo": "2020",
        "door": "Doors",
        "doorNo": "4/5",
        "ac": "AC",
        "acYes": "Yes",
        "tran": "Transmission",
        "tranManual": "Automatic",
        "fuel": "Fuel",
        "fuelDis": "Electric",
        "image": "Assets/car7.jpg",
    },
    {
        "id": 5,
        "model": "Model",
        "name": "VW",
        "mark": "Mark",
        "markNo": "Passat CC",
        "year": "Year",
        "yearNo": "2017",
        "door": "Doors",
        "doorNo": "4/5",
        "ac": "AC",
        "acYes": "Yes",
        "tran": "Transmission",
        "tranManual": "Manual",
        "fuel": "Fuel",
        "fuelDis": "Gasoline",
        "image": "Assets/car6.jpg",
    },
    
]

